name: grits-docs
channels:
  - conda-forge
dependencies:
  - ipython
  - Jinja2
  - numpydoc
  - sphinx==7.2.4
  - sphinx_rtd_theme==1.3.0
  - cmeutils
  - ele
  - freud>=3.0,<3.2
  - gsd
  - mbuild>=0.17
  - numpy
  - openbabel
