name: grits-docs
channels:
  - conda-forge
dependencies:
  - ipython
  - Jinja2
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - cmeutils
  - ele
  - freud>=3.0,<3.2
  - gsd
  - mbuild>=0.17
  - numpy
  - openbabel
